name: Run Weather Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Run weather monitor
        run: dotnet run --project weather_monitor.csproj
